/**
 * @file Questions.gs
 * @description 120 questões psicométricas organizadas em 8 eixos temáticos
 *              de 15 questões cada, consumidas pelo FormsAPI.gs via addScaleItem(1–10).
 *              O Eixo 8 (Q106–Q120) aborda cumplicidade estrutural e simbiose
 *              crime-finanças, derivado da reportagem "A Simbiose" (piauí, 2026).
 * @module Módulo2_Formularios
 * @version 3.0.0
 * @date 2026-04-30
 */

function getDiagnosticQuestions() {
  return [
    // EIXO 1: Regulação Financeira e Banco Central (Q1–Q15)
    {id:'Q1',  axis:1, title:'O mercado financeiro se autorregula sem necessidade de um Banco Central ativo.'},
    {id:'Q2',  axis:1, title:'A autonomia do Banco Central é essencial para a estabilidade econômica.'},
    {id:'Q3',  axis:1, title:'O FGC protege adequadamente os pequenos investidores.'},
    {id:'Q4',  axis:1, title:'Taxas de CDB acima de 130% do CDI são sinal de risco sistêmico.'},
    {id:'Q5',  axis:1, title:'A fiscalização do BC deveria impedir instituições de oferecer taxas irreais.'},
    {id:'Q6',  axis:1, title:'A concentração bancária é prejudicial à competitividade do setor financeiro.'},
    {id:'Q7',  axis:1, title:'Bancos de médio porte devem ter exigências de capital tão rigorosas quanto grandes bancos.'},
    {id:'Q8',  axis:1, title:'A emissão de CDBs sem lastro deveria ser criminalizada.'},
    {id:'Q9',  axis:1, title:'O limite de R$ 250 mil do FGC por CPF é suficiente para proteger investidores de varejo.'},
    {id:'Q10', axis:1, title:'A supervisão prudencial do BC falhou em detectar deterioração de liquidez em instituições recentes.'},
    {id:'Q11', axis:1, title:'Operações interbancárias com carteiras de crédito deveriam ser auditadas por entidades independentes.'},
    {id:'Q12', axis:1, title:'O sigilo bancário deve prevalecer durante investigações de fraude financeira.'},
    {id:'Q13', axis:1, title:'A política monetária deve ser determinada por critérios técnicos, sem interferência política.'},
    {id:'Q14', axis:1, title:'O BC deveria poder vetar fusões que concentrem risco sistêmico.'},
    {id:'Q15', axis:1, title:'A reposição do FGC após crise bancária encarece o crédito para toda a sociedade.'},
    // EIXO 2: Papel do Estado na Economia (Q16–Q30)
    {id:'Q16', axis:2, title:'A intervenção estatal é necessária para prevenir crises financeiras.'},
    {id:'Q17', axis:2, title:'Bancos públicos devem poder socorrer bancos privados em dificuldade.'},
    {id:'Q18', axis:2, title:'A privatização de bancos estatais reduziria a corrupção no setor.'},
    {id:'Q19', axis:2, title:'Fundos de previdência devem ser impedidos de investir em títulos de bancos de médio porte.'},
    {id:'Q20', axis:2, title:'O Estado deve resgatar depositantes quando um banco privado falir.'},
    {id:'Q21', axis:2, title:'A desregulamentação financeira de governos recentes contribuiu para fraudes.'},
    {id:'Q22', axis:2, title:'Políticas de livre mercado geram mais benefícios que riscos ao sistema financeiro.'},
    {id:'Q23', axis:2, title:'O governo deveria estabelecer tetos para taxas de captação.'},
    {id:'Q24', axis:2, title:'Parcerias Público-Privadas em infraestrutura financeira geram conflitos de interesse.'},
    {id:'Q25', axis:2, title:'O Estado é diretamente responsável quando pensionistas perdem recursos em bancos sem garantia.'},
    {id:'Q26', axis:2, title:'A abertura de capital de bancos menores deveria ser incentivada para transparência.'},
    {id:'Q27', axis:2, title:'Governos de esquerda são mais eficazes na regulação do mercado financeiro.'},
    {id:'Q28', axis:2, title:'Governos de direita criam condições para fraudes por desregulamentação excessiva.'},
    {id:'Q29', axis:2, title:'A tributação de grandes fortunas poderia financiar proteção ao investidor.'},
    {id:'Q30', axis:2, title:'A autonomia de bancos estatais é comprometida por nomeações políticas.'},
    // EIXO 3: Justiça e Accountability (Q31–Q45)
    {id:'Q31', axis:3, title:'Ministros do STF com contratos investigados devem se declarar impedidos automaticamente.'},
    {id:'Q32', axis:3, title:'A prisão preventiva de executivos financeiros antes da condenação é justificável.'},
    {id:'Q33', axis:3, title:'Parentes de autoridades não devem prestar serviços a instituições sob investigação.'},
    {id:'Q34', axis:3, title:'A delação premiada é eficaz para combater crimes de colarinho branco.'},
    {id:'Q35', axis:3, title:'O foro privilegiado protege indevidamente autoridades em crimes financeiros.'},
    {id:'Q36', axis:3, title:'Investigações de fraude devem ter acesso irrestrito a dados bancários.'},
    {id:'Q37', axis:3, title:'Sigilo judicial em casos de fraude bancária prejudica o interesse público.'},
    {id:'Q38', axis:3, title:'Magistrados que se declaram suspeitos tardiamente deveriam sofrer sanções.'},
    {id:'Q39', axis:3, title:'A PF é a instituição mais preparada para investigar crimes financeiros complexos.'},
    {id:'Q40', axis:3, title:'Milícias privadas contratadas por banqueiros configuram crime hediondo.'},
    {id:'Q41', axis:3, title:'Consultorias milionárias de ex-ministros a bancos constituem tráfico de influência.'},
    {id:'Q42', axis:3, title:'O COAF deve ter mais autonomia para rastrear movimentações suspeitas.'},
    {id:'Q43', axis:3, title:'Evasão para paraísos fiscais durante investigações deveria gerar bloqueio imediato.'},
    {id:'Q44', axis:3, title:'O TCU deveria investigar decisões do liquidante do Banco Central.'},
    {id:'Q45', axis:3, title:'A punição para colarinho branco é desproporcional comparada a crimes comuns.'},
    // EIXO 4: Transparência e Fiscalização (Q46–Q60)
    {id:'Q46', axis:4, title:'Doações eleitorais de executivos do setor financeiro deveriam ser proibidas.'},
    {id:'Q47', axis:4, title:'Lobbying para alterar limites do FGC configura crime econômico.'},
    {id:'Q48', axis:4, title:'Dados do COAF sobre movimentações de políticos devem ser públicos.'},
    {id:'Q49', axis:4, title:'Empresas de fachada para simular carteiras devem gerar responsabilidade solidária.'},
    {id:'Q50', axis:4, title:'Auditorias externas obrigatórias previnem fraudes em balanços financeiros.'},
    {id:'Q51', axis:4, title:'Transparência corporativa é mais importante que lucro dos acionistas.'},
    {id:'Q52', axis:4, title:'Órgãos reguladores devem publicar relatórios de risco em tempo real.'},
    {id:'Q53', axis:4, title:'O jornalismo investigativo é o principal instrumento de exposição de fraudes.'},
    {id:'Q54', axis:4, title:'Whistleblowers de fraudes financeiras devem receber proteção legal abrangente.'},
    {id:'Q55', axis:4, title:'Gestões de fundos de previdência estaduais devem ser obrigatoriamente auditadas.'},
    {id:'Q56', axis:4, title:'CPIs são eficazes para fiscalizar o setor financeiro.'},
    {id:'Q57', axis:4, title:'Nomeação de diretores do BC deveria exigir quarentena do setor privado.'},
    {id:'Q58', axis:4, title:'Offshores de controladores de bancos deveriam ser reportadas ao COAF automaticamente.'},
    {id:'Q59', axis:4, title:'O sistema brasileiro de registro empresarial facilita ocultação de patrimônio.'},
    {id:'Q60', axis:4, title:'Relatórios do BC sobre instituições em dificuldade devem ser divulgados antes da liquidação.'},
    // EIXO 5: Mídia, Informação e Viés (Q61–Q75)
    {id:'Q61', axis:5, title:'A cobertura da mídia sobre escândalos financeiros é frequentemente enviesada.'},
    {id:'Q62', axis:5, title:'Veículos de comunicação omitem seletivamente fatos para proteger aliados políticos.'},
    {id:'Q63', axis:5, title:'Bolhas algorítmicas dificultam a compreensão factual de crises.'},
    {id:'Q64', axis:5, title:'Redes sociais são fontes confiáveis sobre fraudes financeiras.'},
    {id:'Q65', axis:5, title:'Cidadãos avaliam objetivamente crises financeiras sem ferramentas de auditoria.'},
    {id:'Q66', axis:5, title:'A desinformação sobre o sistema financeiro é mais perigosa que a própria fraude.'},
    {id:'Q67', axis:5, title:'O fact-checking é eficaz contra narrativas enviesadas sobre crises bancárias.'},
    {id:'Q68', axis:5, title:'Analistas econômicos de TV são mais influenciados por patrocinadores que por evidências.'},
    {id:'Q69', axis:5, title:'A polarização política impede responsabilização bipartidária em escândalos.'},
    {id:'Q70', axis:5, title:'Jornalistas que expõem fraudes devem ter proteção estatal contra intimidação.'},
    {id:'Q71', axis:5, title:'A concentração de propriedade de mídia compromete imparcialidade na cobertura financeira.'},
    {id:'Q72', axis:5, title:'É possível avaliar objetivamente fatos que implicam seu próprio espectro político.'},
    {id:'Q73', axis:5, title:'Algoritmos são mais confiáveis que jornalistas para detectar viés mediático.'},
    {id:'Q74', axis:5, title:'Acesso a documentos processuais é mais importante que privacidade dos envolvidos.'},
    {id:'Q75', axis:5, title:'Cegueira tribal é o maior obstáculo à verdade factual.'},
    // EIXO 6: Governança Corporativa e Ética (Q76–Q90)
    {id:'Q76', axis:6, title:'Banqueiros fraudadores devem ser permanentemente banidos do mercado financeiro.'},
    {id:'Q77', axis:6, title:'Empresas de fachada para inflar patrimônio geram responsabilidade criminal solidária.'},
    {id:'Q78', axis:6, title:'Remuneração variável de executivos bancários contribui para riscos excessivos.'},
    {id:'Q79', axis:6, title:'Conselheiros independentes em bancos de médio porte deveriam ser obrigatórios.'},
    {id:'Q80', axis:6, title:'Lucros privatizados e prejuízos socializados são inerentes ao capitalismo financeiro.'},
    {id:'Q81', axis:6, title:'Códigos de ética voluntários são insuficientes para prevenir fraudes financeiras.'},
    {id:'Q82', axis:6, title:'A estrutura de incentivos bancários favorece comportamentos predatórios de captação.'},
    {id:'Q83', axis:6, title:'Bancos com taxas acima da média devem ser monitorados em tempo real.'},
    {id:'Q84', axis:6, title:'O compliance atual das instituições financeiras é apenas cosmético.'},
    {id:'Q85', axis:6, title:'Separação entre banco comercial e de investimento reduziria risco sistêmico.'},
    {id:'Q86', axis:6, title:'Holdings financeiras devem publicar balanços consolidados trimestrais.'},
    {id:'Q87', axis:6, title:'O sistema financeiro brasileiro é resiliente a crises do porte do caso Master.'},
    {id:'Q88', axis:6, title:'A interconexão entre instituições amplifica risco de contágio sistêmico.'},
    {id:'Q89', axis:6, title:'Responsabilidade criminal de sócios controladores deveria ser presumida em fraude contábil.'},
    {id:'Q90', axis:6, title:'Liquidação extrajudicial é o mecanismo mais eficiente para insolvências bancárias.'},
    // EIXO 7: Direitos do Consumidor e Proteção do Investidor (Q91–Q105)
    {id:'Q91',  axis:7, title:'Investidores de varejo são as principais vítimas de captação fraudulenta.'},
    {id:'Q92',  axis:7, title:'Educação financeira é suficiente para proteger cidadãos de fraudes bancárias.'},
    {id:'Q93',  axis:7, title:'Quem investe em CDBs com taxas irreais assume parte do risco de perda.'},
    {id:'Q94',  axis:7, title:'Seguradoras devem cobrir perdas de investidores em fraude bancária comprovada.'},
    {id:'Q95',  axis:7, title:'Pensionistas estaduais merecem proteção especial contra gestores negligentes.'},
    {id:'Q96',  axis:7, title:'Proteção do investidor é mais importante que liberdade de captação dos bancos.'},
    {id:'Q97',  axis:7, title:'O aumento do FGC para R$ 1 milhão beneficiaria exclusivamente grandes aplicadores.'},
    {id:'Q98',  axis:7, title:'Plataformas devem ser responsabilizadas por distribuir produtos de bancos insolventes.'},
    {id:'Q99',  axis:7, title:'O investidor tem direito à informação completa sobre a saúde financeira do emissor.'},
    {id:'Q100', axis:7, title:'Ações coletivas de investidores lesados são mais eficientes que processos individuais.'},
    {id:'Q101', axis:7, title:'A velocidade de ressarcimento pelo FGC é tão importante quanto o montante garantido.'},
    {id:'Q102', axis:7, title:'O efeito contracionista do resgate pelo FGC é um preço aceitável pela estabilidade.'},
    {id:'Q103', axis:7, title:'Regulação financeira deve priorizar o consumidor sobre a liberdade operacional dos bancos.'},
    {id:'Q104', axis:7, title:'O sistema financeiro deveria ter um canal público de denúncias acessível a qualquer cidadão.'},
    {id:'Q105', axis:7, title:'A gravidade do escândalo Master justifica criação de uma CPMI no Congresso.'},
    // EIXO 8: Cumplicidade Estrutural e Simbiose Crime-Finanças (Q106–Q120)
    // Derivado da reportagem "A Simbiose" (piauí, 2026): a Faria Lima como ecossistema
    // que absorve, normaliza e reorganiza ilegalidades independentemente de partido.
    {id:'Q106', axis:8, title:'O mercado financeiro como um todo é cúmplice quando tolera atores sabidamente irregulares.'},
    {id:'Q107', axis:8, title:'A "autorregulação" via entidades como a Anbima é um mecanismo eficaz de controle.'},
    {id:'Q108', axis:8, title:'Bancos que distribuem CDBs de instituições com sinais de fraude devem ser responsabilizados.'},
    {id:'Q109', axis:8, title:'Auditorias e agências de risco que chancelam balanços fraudulentos devem responder criminalmente.'},
    {id:'Q110', axis:8, title:'A convivência do mercado com gestoras como a Reag indica falha sistêmica, não casos isolados.'},
    {id:'Q111', axis:8, title:'Eufemismos financeiros (como "assimetria informacional" para fraude) obscurecem a gravidade dos crimes.'},
    {id:'Q112', axis:8, title:'O uso de fundos exclusivos e fechados para ocultar beneficiários deveria ser proibido.'},
    {id:'Q113', axis:8, title:'A Faria Lima opera como um ecossistema onde crime organizado e finanças convivem simbioticamente.'},
    {id:'Q114', axis:8, title:'Gestores que atacam programas sociais mas silenciam sobre fraudes do próprio setor praticam hipocrisia.'},
    {id:'Q115', axis:8, title:'O subsídio tributário ao rentista (isenções de IR sobre investimentos) é tão questionável quanto o Bolsa Família.'},
    {id:'Q116', axis:8, title:'A captura dos Três Poderes pelo Master demonstra que a corrupção financeira é transpartidária.'},
    {id:'Q117', axis:8, title:'Fundos de previdência estaduais são deliberadamente deixados vulneráveis por falta de fiscalização.'},
    {id:'Q118', axis:8, title:'Profissionais com pedigree de instituições prestigiadas (Garantia, Credit Suisse) legitimam operações ilícitas.'},
    {id:'Q119', axis:8, title:'A destruição de empresas produtivas (como a Oncoclínicas) pelo sistema financeiro deveria gerar punição exemplar.'},
    {id:'Q120', axis:8, title:'O silêncio do mercado diante de irregularidades conhecidas é tão grave quanto a fraude em si.'}
  ];
}
